name: "CI"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Nix Cache
      uses: actions/cache@v3
      with:
        path: nix-store-cache
        key: ${{ matrix.name }}-nix-store-cache-${{ github.sha }}
        # fall back to (latest) previous cache
        restore-keys: |
          ${{ matrix.name }}-nix-store-cache
    - run: |
        cp -r nix-store-cache nix-store-cache-copy || true
    - uses: cachix/install-nix-action@v18
      with:
        # https://github.com/NixOS/nix/issues/6572
        install_url: https://releases.nixos.org/nix/nix-2.7.0/install
        extra_nix_config: |
          extra-substituters = file://${{ github.workspace }}/nix-store-cache-copy?priority=10&trusted=true https://lean4.cachix.org/
          extra-trusted-public-keys = lean4.cachix.org-1:mawtxSxcaiWE24xCXXgh3qnvlTkyU7evRRnGeAhD4Wk=
    - run: |
        nix build . .#book -o push -L
        nix build .#book
        cp --recursive --dereference --no-preserve=mode,ownership result public
      shell: nix run .#ciShell -- bash -euxo pipefail {0}
    - uses: actions/upload-pages-artifact@v1
      with:
        path: './public'
    - name: Rebuild Nix Store Cache
      run: |
        rm -rf nix-store-cache || true
        nix copy ./push* --to file://$PWD/nix-store-cache?compression=none

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
